[package]
name = "bbl-backend"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bbl-frontend = { path = "../frontend" }
cpp_codegen = { path = "../cpp_codegen" }
rand = "0.8"
